version: "3"

services:
  web:
    #image: webdevops/php-apache:alpine-php7
    #Para uso na arquitetura M1:
    build:
      context: ./php-apache-7.4
      dockerfile: ./Dockerfile
    platform: linux/x86_64
    ports:
      - "8080:80"
    volumes:
      - ./www/tematres:/app
    networks:
      - rede

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar
    networks:
      - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar
    ports:
      - "8081:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - rede
networks:
  rede:
    driver: bridge